services:
  backend:
    container_name: movie-backend
    build:
      context: backend
      dockerfile: docker/Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    image: movie-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:${BACKEND_PORT}/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 3s
    environment:
      LOCAL_MODEL: ${LOCAL_MODEL}
      HF_TOKEN: ${HF_TOKEN}
      TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - 22060:${BACKEND_PORT}
      - 22062:8000   # Prometheus Python metrics
    networks:
      - movie_net
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
      args:
        - PORT=${FRONTEND_PORT}
    image: movie-frontend
    environment:
      BACKEND_URL: "http://backend:${BACKEND_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 22061:${FRONTEND_PORT}
      - 22063:8001   # Prometheus Python metrics
    networks:
      - movie_net
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - movie_net
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /:/host:ro
    pid: host
    networks:
      - movie_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - 22066:9090
    networks:
      - movie_net
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
      - cadvisor
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/movie-dashboard.json:/var/lib/grafana/dashboards/movie-dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 22067:3000
    networks:
      - movie_net
    restart: unless-stopped
    depends_on:
      - prometheus

  ngrok_frontend:
    image: ngrok/ngrok:latest
    depends_on:
    - frontend
    command: 
    - http
    - frontend:${FRONTEND_PORT}
    networks:
    - movie_net
    environment:
      NGROK_AUTHTOKEN: ${NGROK_FRONTEND_AUTHTOKEN}
    restart: unless-stopped

  ngrok_grafana:
    image: ngrok/ngrok:latest
    depends_on:
    - grafana
    command:
    - http
    - grafana:3000
    networks:
    - movie_net
    environment:
      NGROK_AUTHTOKEN: ${NGROK_GRAFANA_AUTHTOKEN}
    restart: unless-stopped


networks:
  movie_net:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
