services:
  backend:
    container_name: movie-backend
    build:
      context: backend
      dockerfile: docker/Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    image: movie-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:${BACKEND_PORT}/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 3s
    environment:
      LOCAL_MODEL: ${LOCAL_MODEL}
      HF_TOKEN: ${HF_TOKEN}
      TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - 22060:${BACKEND_PORT}
      - 22062:8000   # Prometheus Python metrics
      - 22064:9100   # Node exporter
    networks:
      - movie_net
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile
      args:
        - PORT=${FRONTEND_PORT}
    image: movie-frontend
    environment:
      BACKEND_URL: "http://backend:${BACKEND_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 22061:${FRONTEND_PORT}
      - 22063:8001   # Prometheus Python metrics
      - 22065:9100   # Node exporter
    networks:
      - movie_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 22066:9090
    networks:
      - movie_net
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/movie-dashboard.json:/var/lib/grafana/dashboards/movie-dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 22067:3000
    networks:
      - movie_net
    restart: unless-stopped
    depends_on:
      - prometheus

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
    - frontend
    command:
    - "http"
    - "http://frontend:${FRONTEND_PORT}"
    networks:
    - movie_net
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    restart: unless-stopped

networks:
  movie_net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
