global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'movie-backend'

  - job_name: 'frontend_app'
    static_configs:
      - targets: ['frontend:8001']
        labels:
          service: 'movie-frontend'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
